### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by hailzfn** [jamnsr/mwclap#3]
Your Project Does not have a main Function
Why??

**Comment by serjam** [comment]
https://github.com/jamnsr/mwclap/blob/700e3bbca3b3562236cd7fc87cdab7257fafe1b7/main.cpp#L7 ?...

**Comment by hailzfn** [comment]
what type of project do you compile it as?

**Comment by jamnsr** [comment]
Application (.exe)

**Comment by serjam** [comment]
> what type of project do you compile it as?

Application (.exe)

**Comment by hailzfn** [comment]
yes I know that but what type of application console, desktop etc? 
on a console app I get a unresolved external on a desktop app nothing shows up it just runs in the background
